name: EC2 deploy from docker

on:
  push:
    branches: ["main"]

jobs:
  login-and-pull-qa:
    uses: ./.github/workflows/login_pull.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_APP1 }}

  login-and-pull-main:
    uses: ./.github/workflows/login_pull.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_APP2 }}

  ssh-connect-ec2-QA01:
    needs: login-and-pull-qa
    uses: ./.github/workflows/setup_docker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_APPTEST }}
      ec2_key: ${{ secrets.EC2_KEY_APPTEST }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}


