name: EC2 deploy from docker

on:
  push:
    branches: ["main"]

jobs:
  login-and-pull-qa:
    if: github.ref == 'refs/heads/QA'
    uses: ./.github/workflows/login_pull.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_QA }}

  login-and-pull-main:
    if: github.event_name == 'pull_request' && github.base_ref == 'main' 
    uses: ./.github/workflows/login_pull.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_PRD }}

  ssh-connect-ec2-QA01:
    needs: [login-and-pull-qa]
    uses: ./.github/workflows/setup_docker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_QA01 }}
      ec2_key: ${{ secrets.EC2_KEY_QA }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_QA }}

  ssh-connect-ec2-QA02:
    needs: [login-and-pull-qa]
    uses: ./.github/workflows/setup_docker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_QA02 }}
      ec2_key: ${{ secrets.EC2_KEY_QA }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_QA }}

  ssh-connect-ec2-PRD01:
    needs: [login-and-pull-main]
    uses: ./.github/workflows/setup_docker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_PRD01 }}
      ec2_key: ${{ secrets.EC2_KEY_PRD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_PRD }}

  ssh-connect-ec2-PRD02:
    needs: [login-and-pull-main]
    uses: ./.github/workflows/setup_docker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_PRD02 }}
      ec2_key: ${{ secrets.EC2_KEY_PRD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_PRD }}

  ssh-connect-ec2-PRD03:
    needs: [login-and-pull-main]
    uses: ./.github/workflows/setup_docker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_PRD03 }}
      ec2_key: ${{ secrets.EC2_KEY_PRD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_PRD }}

  ssh-connect-ec2-PRD04:
    needs: [login-and-pull-main]
    uses: ./.github/workflows/setup_docker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_PRD04 }}
      ec2_key: ${{ secrets.EC2_KEY_PRD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_PRD }}